### ISSUE TITLE
PHP 5.5 requirement?

### ISSUE THREAD

**Issue by brianium** [peridot-php/peridot#141]
I am leaning towards a PHP 5.5 requirement for version 2.0. There has been talk of baking in some core plugins, and PHP 5.5 offers some features that could greatly simplify some things. The biggest gain is generators, and how they simplify non-blocking IO (concurrency).

Some other goodies would be the ability to use non-scalar types in iterators, and dereferencing string literals.

**Comment by brianium** [comment]
@austinsmorris thoughts?

**Comment by austinsmorris** [comment]
:+1:

**Comment by brianium** [comment]
Ok - thinking 5.6 will be the new requirement for 2.0 - I mean we are all adults right?

**Comment by brianium** [comment]
composer.json now enforces php >= 5.6.0 - event emitter now uses variadic arguments.
