### ISSUE TITLE
doctest feature

### ISSUE THREAD

**Issue by brianium** [peridot-php/peridot#142]
It would be pretty sweet to support a feature like elixir and python's doctest.

Docs for elixir's ExUnit can be found [here](http://elixir-lang.org/docs/v1.0/ex_unit/ExUnit.DocTest.html)

**Comment by fesor** [comment]
I think this should be done via separate tool.

**Comment by ragboyjr** [comment]
This would be neat, but definitely should be a separate tool. Also, [Peridocs](https://github.com/krakphp/peridocs) is a somewhat similar tool that might obviate the need for such a tool.

I'm planning on bringing Peridocs into this organization as well.
