### ISSUE TITLE
Slightly goofy globbing

### ISSUE THREAD

**Issue by austinsmorris** [peridot-php/peridot#143]
There is something a little goofy about our globbing when we do <code>SuiteLoader::getTests($path)</code>.

Sometimes there is an extra directory separator in one of the paths:

    specs/Foo/Api/Route/Middleware//register-application-middleware.spec.php

**Comment by brianium** [comment]
I think that is a perfectly valid path still, just not as pretty to look at

**Comment by brianium** [comment]
in the concurrency plugin i look for it to strip it

**Comment by brianium** [comment]
But.... most likely this line:

https://github.com/peridot-php/peridot/blob/master/src/Runner/SuiteLoader.php#L78
