### ISSUE TITLE
trigger_error is not immediately apparent

### ISSUE THREAD

**Issue by JoelLarson** [peridot-php/peridot#157]
```php
<?php

describe('Error', function () {
    context('when a fatal error occurs', function () {
        it('should give me the error and bail', function () {
            trigger_error('This is an error. It should not pass.', E_USER_ERROR);
        });
    });
});
```

In this test specification, the following output occurs:

```
vagrant@localhost:/var/www/project$ ./vendor/bin/peridot tests/spec/Error.spec.php

  Error
    when a fatal error occurs
      ✓ should give me the error and bail


  1 passing (1 ms)
```

It was not immediately apparent to me why this was happening and does not seem like it should be the expected outcome of it. To solve this problem, I did some digging and realized that the Emitter event `error` is triggered and now have it visible by adding this to my configuration file:

```php
return function(\Evenement\EventEmitterInterface $emitter) {
    $emitter->on('error', function ($errorNumber, $errorString, $errorFile, $errorLine) {
        throw new \Exception ("ErrorException Thrown in {$errorFile}:{$errorLine}\n -> {$errorString}", $errorNumber);
    });
};
```

I feel this happening is not very apparent and should be either made apparent in the documentation or corrected to show an error message when a triggered error occurs. Any thoughts on it?

**Comment by brianium** [comment]
Hmmm... interesting. It seemed appropriate to catch errors and make them available via an event to do just what you have done. A true fatal error would cause the tests to stop executing, but user errors would not. Does it make sense to treat E_USER_* errors differently? I see a couple of options here:

1. Do as you suggested and just document this
2. Bake this functionality in and enable via a config (maybe --verbose or some such option?)
3. Treat E_USER_* errors differently and let them through
4. A plugin that effectively does what you have added to the plugin - maybe like `peridot-strict`

This is what comes to mind for me at the moment, but I am definitely open to other options. In the mean time, I will update the docs to be more clear about this behavior. Thoughts?

Also - thanks for opening these issues! It goes a long way in making Peridot better.
