### ISSUE TITLE
Mark test as skipped when dependencies are not met

### ISSUE THREAD

**Issue by JoelLarson** [peridot-php/peridot#159]
I've been writing a package where I'm using an adapter to implement Pimple 1 and Pimple 3. There is a problem with dependencies conflicting with composer, so I would like to be able to mark a spec file as "skipped because of dependency issue" and still mark the test suite as "OK".

PHPUnit has "Mark Test Skipped"

**Comment by brianium** [comment]
@JoelLarson thanks for opening the issue - we had this thought too, and it has already been implemented in the 2.0 branch https://github.com/peridot-php/peridot-core/issues/4

Hopefully we will have a release cut soon!
