### ISSUE TITLE
PHPUnit output?

### ISSUE THREAD

**Issue by mnapoli** [peridot-php/peridot#163]
I'm wondering if it's possible to make Peridot work with PhpStorm. A way to do that might be to run Peridot as "PHPUnit" (i.e. set up to use Peridot's binary instead of PHPUnit), the only thing would be that the output should be similar to PHPUnit so that PhpStorm can parse it. Is there a way to achieve that out of the box?

**Comment by brianium** [comment]
I'm not altogether familiar with how PHPUnit output is parsed by PhpStorm. Does it use a format like junit.xml or tap?

**Comment by brianium** [comment]
Those outputs are not supported out of the box by Peridot, but it should be pretty simple to implement a plugin that accomplishes that

**Comment by mnapoli** [comment]
I understand. From what I've understood of the docs, it should be a custom "reporter" is that right?

(closing the issue, my question has been answered thanks)
