### ISSUE TITLE
Option to output xterm color codes

### ISSUE THREAD

**Issue by vicary** [peridot-php/peridot#165]
My team uses an internal issue tracker that hooks to spec/test creation, which supports a test run for codes written in the browser.

I want to switch from phpunit and try peridot because of the simplicity, but peridot does not support HTTP outputs AFAIK.

Since we have already done console color conversion from `git diff --color=always`, is there anyway we can force console colours in peridot so we can use get the output along with colours like this?

```PHP
$output_with_colors = `peridot --color=always specs/`;
```

**Comment by brianium** [comment]
Thanks for opening the issue. Peridot uses the symfony console component, which tries to detect color support by seeing if the terminal is TTY. We had a similar need for our concurrency plugin so we exposed an environment variable to always flag the terminal as tty (on non windows machines anyways).

https://github.com/peridot-php/peridot/blob/master/src/Reporter/AbstractBaseReporter.php#L282

Maybe try setting that env variable for now and see if that works for you. If that works for you, it should be pretty simple to add a switch like --color-always to the command line.

The reporter API for peridot is pretty simple too if you wanted to write something lightweight for pushing test results over HTTP. Any of the peridot reporters would be a good reference:

https://github.com/peridot-php/peridot-dot-reporter

**Comment by vicary** [comment]
It works with `putenv('PERIDOT_TTY=1');`, I'll use that for now. Not sure how peridot handles CLI arguments, `Peridot\Console\Application` does not seems to have any related code for that.

**Comment by brianium** [comment]
It currently does not support it from the CLI, but take a look at the [InputDefinition](https://github.com/peridot-php/peridot/blob/master/src/Console/InputDefinition.php#L24) - this is where new arguments and options are defined. They can then be handled in the [Command](https://github.com/peridot-php/peridot/blob/master/src/Console/Command.php). Pull requests are of course welcome :)

Glad the env variable helped!
