### ISSUE TITLE
BDD: Peridot and Laravel 5.1

### ISSUE THREAD

**Issue by IngwiePhoenix** [peridot-php/peridot#168]
I prefer the `describe-it` syntax that Peridot offers over PHPUnit, so I would like to use Peridot.

This is what Laravel offers for testing:
http://laravel.com/docs/5.1/testing

Is there a way to use Peridot with that? I would imagine that I would have to construct a new request and kernel (= request handler) during each test.

**Comment by austinsmorris** [comment]
Hi @IngwiePhoenix,

Checkout the [HttpKernel Plugin](https://github.com/peridot-php/peridot-httpkernel-plugin).  That might help you get started with functional tests in Laravel.  I use it personally to test in Silex, and Laravel shares many of the same Symfony components.  Enjoy!
