### ISSUE TITLE
Shorten stack traces on errors and failed tests

### ISSUE THREAD

**Issue by mataps** [peridot-php/peridot#170]
It would be very nice to have an option to see only useful error messages rather than showing the whole stack trace.

**Comment by brianium** [comment]
@mataps agreed. @ezzatron recently submitted a useful [PR](https://github.com/peridot-php/leo/pull/18) to the leo matcher library, maybe this could be integrated into the core.

**Comment by brianium** [comment]
or something similar

**Comment by ezzatron** [comment]
The Leo PR is a bit of a different situation, I think. In that particular case, the exception is always Leo's own exception, so it can be "trimmed" easily by looking at namespaces in the trace.

There are definitely some similarities though. I'll have a look, and see what can be done.

**Comment by ezzatron** [comment]
Actually, @brianium, thinking about it again, this issue is from *before* that Leo PR was accepted. It's quite possible it's referring to Leo's assertion stack traces, and may already be fixed.

@mataps Could you provide some example code / output?

**Comment by ezzatron** [comment]
Never mind my comment above. This is definitely still an issue outside of Leo as well. It shouldn't be a big deal to do something similar for Peridot's traces, like I did for Leo's in peridot-php/leo#18.

**Comment by ezzatron** [comment]
Released in [1.19.0](https://github.com/peridot-php/peridot/releases/1.19.0) 🎉
