### ISSUE TITLE
Integration with Phony

### ISSUE THREAD

**Issue by ezzatron** [peridot-php/peridot#172]
Hi guys, thanks for the work on Peridot, I really like what you've done.

I've written a mocking framework called [Phony](http://eloquent-software.com/phony/) that works pretty well with Peridot. In addition to traditional object mocking, it supports callback spying and stubbing, which fits nicely (at least thematically) with the `describe-it` style. It has support for HHVM and PHP 7, which I noticed you are also targeting.

So I'm creating this issue basically to ask: is there anything more I can do to improve integration with Peridot?

One thing I *do* have planned, is to write a Leo plugin as well, so that you can use `expect` style assertions. But for now, it works fine to use Phony directly. Check out the [Peridot example test suite](https://github.com/eloquent/phony/blob/develop/doc/example/event-emitter/peridot/EventEmitter.spec.php) if you're interested.

Thanks again for the awesome work!

**Comment by brianium** [comment]
Wow. This looks really cool. Functions definitely make this appear simple. I can't really think of a formal integration path with Peridot other than plugins. This would only save having to include the Phony namespace.

Something like adding `mock` and `spy` methods to a Peridot scope:

```php
beforeEach(function() {
  $this->handle = $this->mock(); // $this->mock provided by a plugin
  $this->spyA = $this->spy(); // $this->spy provided by a plugin
});
```

Maybe @austinsmorris has some input?

I will definitely give this a try next time I start a PHP project. Good work.

**Comment by ezzatron** [comment]
@brianium Thanks! You know, strangely, I didn't even think of an actual Peridot plugin, but that *would* make it slightly nicer to use, even if it's only a small thing. I'll check out the plugin system when I get a chance.
