### ISSUE TITLE
Tests always reported as passing?

### ISSUE THREAD

**Issue by pr0ggy** [peridot-php/peridot#182]
I feel like I _have_ to be missing something painfully simple here, but can't for the life of me figure it out.  Started out by pulling in Peridot via Composer (along with a few plugins):
```json
"require-dev": {
    "mockery/mockery": "dev-master",
    "squizlabs/php_codesniffer": "~1.5",
    "peridot-php/peridot": "~1.15",
    "peridot-php/peridot-list-reporter": "^1.0",
    "peridot-php/peridot-code-coverage-reporters": "^2.0"
}
```

I then created a `specs/` folder and within it a `Sample.spec.php` file containing the sample code from the GitHub page:
```php
describe('ArrayObject', function() {
    beforeEach(function() {
        $this->arrayObject = new ArrayObject(['one', 'two', 'three']);
    });

    describe('->count()', function() {
        it("should return the number of items", function() {
            $count = $this->arrayObject->count();
            assert($count === 3, "expected 3");
        });
    });
});
```

All looks peachy:
```
$ vendor/bin/peridot specs/Sample.spec.php

  ArrayObject
      ->count()
        ✓ should return the number of items


  1 passing (0 ms)
```

However, if I change the assertion in attempt to make the test fail...
```php
describe('ArrayObject', function() {
    beforeEach(function() {
        $this->arrayObject = new ArrayObject(['one', 'two', 'three']);
    });

    describe('->count()', function() {
        it("should return the number of items", function() {
            $count = $this->arrayObject->count();
            assert($count === 1, "expected 3");
        });
    });
});
```
...the test still passes:
```
$ vendor/bin/peridot specs/Sample.spec.php

  ArrayObject
      ->count()
        ✓ should return the number of items


  1 passing (0 ms)
```
Using the List reporter also shows the test as passing:
```
$ vendor/bin/peridot specs/Sample.spec.php -r list
  ArrayObject ->count() should return the number of items


  1 passing (0 ms)
```

System info (Linux Mint 18):
```
$ vendor/bin/peridot --version
Peridot version 1.18.1
$ php --version
PHP 7.0.4-7ubuntu2.1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
$ composer show
evenement/evenement                         v2.0.0             Événement is a very simp...
hamcrest/hamcrest-php                       v2.0.0             This is the PHP port of Ha...
mockery/mockery                             dev-master ee06e7b Mockery is a simple yet fl...
peridot-php/peridot                         1.18.1             Event driven BDD test fram...
peridot-php/peridot-code-coverage-reporters 2.0.1              Code coverage reporters fo...
peridot-php/peridot-list-reporter           1.0.0              A list reporter for the Pe...
peridot-php/peridot-scope                   1.3.0              Scopes for function bindin...
phpunit/php-code-coverage                   2.2.4              Library that provides coll...
phpunit/php-file-iterator                   1.4.1              FilterIterator implementat...
phpunit/php-text-template                   1.2.1              Simple template engine.
phpunit/php-timer                           1.0.8              Utility class for timing
phpunit/php-token-stream                    1.4.8              Wrapper around PHP's token...
sebastian/environment                       1.3.7              Provides functionality to ...
sebastian/version                           1.0.6              Library that helps with ma...
squizlabs/php_codesniffer                   1.5.6              PHP_CodeSniffer tokenises ...
symfony/console                             v3.1.2             Symfony Console Component
symfony/polyfill-mbstring                   v1.2.0             Symfony polyfill for the M...
```

**Comment by brianium** [comment]
@pr0ggy - hmmm. wondering if there is something janky going on with `assert`. If you throw a generic exception does it fail the test? Try replacing the `assert` with `throw new Exception('failure!!!');`

**Comment by pr0ggy** [comment]
Replacing the `assert` call with the exception throw produced a failure...looks like `assert` is the culprit.

**Comment by brianium** [comment]
Makes sense. Peridot hijacks assert to have it throw exceptions. That is the default behavior, but Peridot considers any non-exception throwing spec to be passing. Any matcher/assertion library that operates via exceptions will work. There are quite a few out there, but [leo](https://github.com/peridot-php/leo) is our own take on not using native `assert`

**Comment by brianium** [comment]
Not sure how PHP 7 deviated, but we use http://php.net/manual/en/function.assert-options.php to setup a callback to trigger an exception.

**Comment by pr0ggy** [comment]
Understood...based on the `zend.assertions` value of -1, it looks like assertions weren't even compiling and were ignored altogether, which would explain why even using runtime assertion configuration wouldn't work.  I just confirmed that you can leave the `assert.active` and `assert.exception` commented out in `php.ini`, the only important setting is ensuring `zend.assertions` to 1.

**Comment by brianium** [comment]
Awesome. I am going to close this for now, but I think I will update the README to include a note in case this bites someone else in the future. Thanks for opening the issue!

**Comment by pr0ggy** [comment]
No problem sir...plan on digging into Peridot a bit more in the coming weeks, will post back if I run into further strangeness. Played around with it quite a bit today, really digging it so far! Kudos!
