### ISSUE TITLE
Multiple reporters

### ISSUE THREAD

**Issue by davidsoderberg** [peridot-php/peridot#186]
Hi, it would be nice to run multiple reporters in the same run.

**Comment by ezzatron** [comment]
I'm re-opening this issue because I know others have had the same thought before, and this can serve as a place to discuss the idea.

**Comment by ezzatron** [comment]
@davidsoderberg Please see #202, and the [multiple-reporters](https://github.com/peridot-php/peridot/tree/multiple-reporters) branch for a prototype of this feature.
