### ISSUE TITLE
setParent() claims to return mixed|void, should omit @return

### ISSUE THREAD

**Issue by ezzatron** [peridot-php/peridot#206]
See https://github.com/peridot-php/peridot/blob/21ae9954b4f02d6c347f1ed26633b367a7652ee5/src/Core/AbstractTest.php#L131

**Comment by ragboyjr** [comment]
@ezzatron want to make a PR for this?

**Comment by ezzatron** [comment]
I don't have the time for it right now, unfortunately. If you'd like to close, that's fine. Same goes for the other issue I raised. Sorry!
