### ISSUE TITLE
Issues with global varables and nested functions

### ISSUE THREAD

**Issue by SteveALee** [peridot-php/peridot#215]
I'm liking Peridot after returning to PHP after a break having been steeped in JavaScript land. The runner and BDD style mean errors are presented nicely. I'm using the native assert with equality tests so the runner shows actuall vs expected when a failure occurs.

I hit 2 strange effects on my code causing me to rewrite so the code still worked

- global vars stop being global. Ie a variable declared at file scope and then referenced form a function with global fail. It seem file scope is not global when running the tests. The solution is to declare the file scope variable as global too. (in case you wonder I only have global vars as static vars in a function cannot be initialised with a dynamic exression :( )

- Nested functions give a weird "already defined" error. This is truely puzzling I had to move the function definitons to file scope. and then all is well.

**Comment by brianium** [comment]
Hey @SteveALee - I'm glad you like peridot. I am the original author, and I don't think it is being maintained anymore. If you like the `describe/it` syntax in PHP, I would recommend checking out [kahlan](https://github.com/kahlan/kahlan). It has better docs and is actively maintained :)

Hope it helps!

**Comment by SteveALee** [comment]
Hey, 

I had to choose on or the other an picked yours. Lol. Thanks for letting me know. That's most excellent.

Interesting yours gets attention in current reviews. But I noticed the lack of activity when raising this issue.

Anyway it works for now and hopefully the test syntax is similar:)
